### PR TITLE
issue fixed:Dark Mode Setting Not Persisting After Page Refresh

### PR DESCRIPTION
**Pull request by Sakyasekhar**
## Attaching the video of dark mode persisting after page refresh.

https://github.com/user-attachments/assets/7c6c8df6-eda0-4a1c-bfec-1b208c630fb1

### CODE REVIEW

**Comment by TheOpenInnovator** [comment]
Hey @Sakyasekhar It seems like there are some conflicts in the code. Please resolve them. There is one more thing.
- when the dark mode is toggled, it should be shown as Toggle Light Theme when in dark theme and vice-versa.

Please do fix these.

**Comment by Sakyasekhar** [comment]
> Hey @Sakyasekhar It seems like there are some conflicts in the code. Please resolve them. There is one more thing.
> - when the dark mode is toggled, it should be shown as Toggle Light Theme when in dark theme and vice-versa.
> 
> Please do fix these.


Ok , I will work on it.

**Comment by TheOpenInnovator** [comment]
> > Hey @Sakyasekhar It seems like there are some conflicts in the code. Please resolve them. There is one more thing.
> > 
> > * when the dark mode is toggled, it should be shown as Toggle Light Theme when in dark theme and vice-versa.
> > 
> > Please do fix these.
> 
> Ok , I will work on it. Sorry for that, I am new to open source.

No worries, keep contributing you will learn and do great.

**Comment by Sakyasekhar** [comment]
> > > Hey @Sakyasekhar It seems like there are some conflicts in the code. Please resolve them. There is one more thing.
> > > 
> > > * when the dark mode is toggled, it should be shown as Toggle Light Theme when in dark theme and vice-versa.
> > > 
> > > Please do fix these.
> > 
> > Ok , I will work on it. Sorry for that, I am new to open source.
> 
> No worries, keep contributing you will learn and do great.

Sure , thank you ☺️

**Comment by TheOpenInnovator** [comment]
Hey @Sakyasekhar Still there's an issue which you can fix.

**- In the Light Theme :** 
image

**- In the Dark Theme :** 
image

In both the cases, it's showing Toggle Dark Theme. But it shouldn't. So you can fix this and raise a PR.

**Comment by TheOpenInnovator** [comment]
@Sakyasekhar Since you said you're still learning, so you can compare the PR which was submitted before you on the same issue and figure out what better and different can I do from that PR and start working on that. So this will also help you to learn and do better and will also help your PR get merged. 

Take your chance.

**Comment by Sakyasekhar** [comment]
> @Sakyasekhar Since you said you're still learning, so you can compare the PR which was submitted before you on the same issue and figure out what better and different can I do from that PR and start working on that. So this will also help you to learn and do better and will also help your PR get merged.
> 
> Take your chance.

Thank you for advice☺️, I will implement it from now.

**Pull request closed without merging**
