### PR TITLE
Enhance CSS for Improved UI/UX

### PR DESCRIPTION
**Pull request by KrishnaSaxena108**
Hi @TheOpenInnovator 

This CSS defines a modern, responsive design with a focus on clean UI/UX. It includes custom colors, gradients, and animations, along with styled components like buttons, input fields, sections, and task lists. It also provides a dark theme option and ensures compatibility with mobile devices using media queries for responsiveness.

Kindly accept the pull request and merge it after reviewing it under HacktoberFest 2024.
Thankyou

Screenshot 2024-10-06 154102
Screenshot 2024-10-06 154116

### CODE REVIEW

**Comment by TheOpenInnovator** [comment]
Hi @KrishnaSaxena108 , the whole enhancement is good looking. But there is something you have to fix : 

1) While the dark theme is toggled, the task entered is not clearly visible. You can see it in the below attached ss. 
2) Reduce the size of the task created. Keep it medium to small size of the task created.

Please fix these and also look if any other enhancements can be done. The overall look has been improved a lot. 


The Screen Shot : 
product ss 1

**Comment by KrishnaSaxena108** [comment]
Thanks @TheOpenInnovator I will surely do this changes as soon as possible

**Comment by KrishnaSaxena108** [comment]
I have done the necessary changes.

Kindly accept my pull request and merge it after reviewing and also don't forget to add the label of HactoberFest 2024

Thankyou

Screenshot 2024-10-06 181522

**Comment by TheOpenInnovator** [comment]
Hi @KrishnaSaxena108 The mentioned were implemented but still there is an enhancement required as shown in the below Screenshots.

In the dark mode, the completed task is not visible.

**When Task is not completed but only added to the task list :** 
image

**When task is completed :** 
image

Please fix this.

**Comment by KrishnaSaxena108** [comment]
Alright I will fix this issue as soon as possible

**Comment by KrishnaSaxena108** [comment]
I have done the necessary changes kindly merge my pull request
Thankyou
Screenshot 2024-10-07 174929

**Comment by TheOpenInnovator** [comment]
@KrishnaSaxena108 Congratulations, your PR has been merged. Thank you for your contribution

**Pull request merged**
