### PR TITLE
UI redesigned for both modes and responsiveness made

### PR DESCRIPTION
**Pull request by nileshkr022**
Redesigned the UI for a smooth experience in both light and dark mode and made the site responsive for use in mobile devices.

### CODE REVIEW

**Comment by TheOpenInnovator** [comment]
Hey @nileshkr022 the overall changes are good, but can you enhance the Dark Mode a little bit more exclusive. 

Along with the dark mode, also enhance the styling of these two which are mentioned in the red box in the below attached screen shot.
image

**Comment by nileshkr022** [comment]
> Hey @nileshkr022 the overall changes are good, but can you enhance the Dark Mode a little bit more exclusive. 
> 
> Along with the dark mode, also enhance the styling of these two which are mentioned in the red box in the below attached screen shot.
> image
> 

Can you elaborate what kind of changes you expect in dark mode

**Comment by nileshkr022** [comment]
@TheOpenInnovator I found this UI to be the best considering the eye strain people get by sitting hours in front of screen

**Comment by TheOpenInnovator** [comment]
@nileshkr022 Just make it more darker if possible, cause it seems like a shade of grey, so make it a shiny black which represents a premium dark theme UI

**Comment by nileshkr022** [comment]
> @nileshkr022 Just make it more darker if possible, cause it seems like a shade of grey, so make it a shiny black which represents a premium dark theme UI
> 

I have made the dark more darker and added vibrant colors to timer so they stand out.

**Pull request merged**
